const employees = [
  {
    id: 1,
    name: "Ali",
    email: "e1@company.com",
    password: "123",
    role: "employee",
    taskCounts: {
      active: "1",
      newTask: "1",
      completed: "1",
      failed: "1",
    },
    tasks: [
      {
        taskId: 1,
        title: "Submit Daily Report",
        description: "Submit daily progress report to manager",
        date: "2025-09-01",
        category: "Reporting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskId: 2,
        title: "Fix Login Bug",
        description: "Resolve login issue reported by users",
        date: "2025-09-02",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 3,
        title: "Client Meeting",
        description: "Attend meeting with client for requirement discussion",
        date: "2025-09-03",
        category: "Meeting",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },

  {
    id: 2,
    name: "Sara",
    email: "e2@company.com",
    password: "123",
    role: "employee",
    taskCounts: {
      active: "2",
      newTask: "1",
      completed: "1",
      failed: "1",
    },
    tasks: [
      {
        taskId: 1,
        title: "Design Dashboard UI",
        description: "Create dashboard UI using Figma",
        date: "2025-09-01",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskId: 2,
        title: "Update Style Guide",
        description: "Update company design system",
        date: "2025-09-04",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 3,
        title: "Prepare Presentation",
        description: "Prepare slides for weekly review",
        date: "2025-09-05",
        category: "Presentation",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskId: 4,
        title: "Review UX Feedback",
        description: "Analyze feedback from users",
        date: "2025-09-06",
        category: "UX",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 3,
    name: "Usman",
    email: "e3@company.com",
    password: "123",
    role: "employee",
    taskCounts: {
      active: "2",
      newTask: "1",
      completed: "2",
      failed: "1",
    },
    tasks: [
      {
        taskId: 1,
        title: "API Integration",
        description: "Integrate payment gateway API",
        date: "2025-09-02",
        category: "Backend",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskId: 2,
        title: "Database Backup",
        description: "Take full database backup",
        date: "2025-09-03",
        category: "Database",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 3,
        title: "Optimize Queries",
        description: "Improve slow SQL queries",
        date: "2025-09-04",
        category: "Optimization",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: 4,
        title: "Server Health Check",
        description: "Monitor server performance",
        date: "2025-09-05",
        category: "DevOps",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskId: 5,
        title: "Write API Docs",
        description: "Document API endpoints",
        date: "2025-09-06",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    name: "Ayesha",
    email: "e4@company.com",
    password: "123",
    role: "employee",
    taskCounts: {
      active: "2",
      newTask: "1",
      completed: "1",
      failed: "1",
    },
    tasks: [
      {
        taskId: 1,
        title: "Prepare Test Cases",
        description: "Write test cases for new features",
        date: "2025-09-02",
        category: "Testing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskId: 2,
        title: "Bug Verification",
        description: "Verify fixed bugs in staging environment",
        date: "2025-09-03",
        category: "QA",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 3,
        title: "Regression Testing",
        description: "Perform regression testing",
        date: "2025-09-04",
        category: "Testing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskId: 4,
        title: "Test Automation Script",
        description: "Create automation script for login flow",
        date: "2025-09-05",
        category: "Automation",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    name: "Hamza",
    email: "e5@company.com",
    password: "123",
    role: "employee",
    taskCounts: {
      active: "2",
      newTask: "1",
      completed: "2",
      failed: "1",
    },
    tasks: [
      {
        taskId: 1,
        title: "Deploy Build",
        description: "Deploy latest build to production",
        date: "2025-09-01",
        category: "Deployment",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskId: 2,
        title: "Monitor Logs",
        description: "Monitor application logs for errors",
        date: "2025-09-02",
        category: "Monitoring",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskId: 3,
        title: "Fix Production Bug",
        description: "Resolve critical bug in production",
        date: "2025-09-03",
        category: "Bug Fix",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskId: 4,
        title: "Server Optimization",
        description: "Optimize server response time",
        date: "2025-09-04",
        category: "DevOps",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskId: 5,
        title: "Write Deployment Docs",
        description: "Document deployment steps",
        date: "2025-09-05",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 100,
    name: "Admin",
    email: "admin@company.com",
    password: "taskIdmin123",
    role: "admin",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employeeData = JSON.parse(localStorage.getItem("employees"));
  const adminData = JSON.parse(localStorage.getItem("admin"));
  return { employeeData, adminData };
};
